service:
  name: codebuild-slack-notifier

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  memorySize: 128
  runtime: nodejs6.10
  region: eu-west-1
  environment:
    SLACK_TOKEN: ${ssm:/codebuild-slack-notifier/SLACK_TOKEN~true}

functions:
  main:
    handler: index.handler
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.codebuild"
            detail-type:
              - "CodeBuild Build State Change"

