service:
  name: ${self:custom.package.name}

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-pseudo-parameters

custom:
  package: ${file(./package.json)}

provider:
  name: aws
  stage: ${opt:stage, 'tools'}
  memorySize: 512
  runtime: nodejs8.10
  timeout: 30
  region: ${opt:region, 'us-west-2'}
  environment:
    DEBUG: ${self:custom.env.DEBUG, 'true'}
    TRACE: ${self:custom.env.TRACE, 'true'}
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    VERSION: ${self:custom.package.version}
    GIT_COMMIT_SHA: ${file(./env/gitCommitSha.js):gitCommitSHA}
    SERVICE: ${self:service.name}
    S3_SLACK_COMMIT_BUCKET: cb-to-slack-tools-serverlessdeploymentbucket-1ndhem0ioiw1k

package:
  individually: true

functions:
  PostUpdateToSlack:
    handler: index.handler
    reservedConcurrency: 2
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ssm:GetParameter
        Resource:
          - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/codebuild-slack-notifier/*
    events:
      - cloudwatchEvent:
          event:
            source:
              - 'aws.codebuild'
            detail-type:
              - 'CodeBuild Build State Change'
              - 'CodeBuild Build Phase Change'
      - cloudwatchEvent:
          event:
            source:
              - 'aws.codepipeline'
            detail-type:
              - 'CodePipeline Pipeline Execution State Change'
              - 'CodePipeline Stage Execution State Change'
              - 'CodePipeline Action Execution State Change'
