service:
  name: ${self:custom.package.name}

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-pseudo-parameters

custom:
  package: ${file(./package.json)}

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  runtime: nodejs8.10
  timeout: 15
  region: ${opt:region, 'eu-west-1'}

package:
  individually: true

functions:
  PostUpdateToSlack:
    handler: index.handler
    reservedConcurrency: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ssm:GetParametersByPath
        Resource:
          - arn:aws:ssm:${self:provider.region}:#{AWS::AccountId}:parameter/codebuild-slack-notifier
    events:
      - cloudwatchEvent:
          event:
            source:
              - 'aws.codebuild'
            detail-type:
              - 'CodeBuild Build State Change'
              - 'CodeBuild Build Phase Change'
      - cloudwatchEvent:
          event:
            source:
              - 'aws.codepipeline'
            detail-type:
              - 'CodePipeline Pipeline Execution State Change'
              - 'CodePipeline Stage Execution State Change'
              - 'CodePipeline Action Execution State Change'
